name: Release

on:
  push:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        id: release
        with:
          release-type: simple
          token: ${{ secrets.GH_TOKEN }}

  build:
    name: Build & Upload Artifacts
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    needs:
      - release-please
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Build and upload release artifacts
        env:
          FOUNDRY_BUILD_RELEASE_VERSION: ${{ needs.release-please.outputs.tag_name }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          just build
          module_id=$(jq -r '.id' foundry-manifest.json)
          zip_file="${module_id}_${FOUNDRY_BUILD_RELEASE_VERSION}.zip"
          (cd dist && zip -r "../$zip_file" *)
          gh release upload "$FOUNDRY_BUILD_RELEASE_VERSION" ./dist/module.json "$zip_file"
